services:
  postgres:
    image: postgres:17-alpine
    container_name: obstanovka-db-alt
    restart: unless-stopped
    environment:
      POSTGRES_USER: facilities
      POSTGRES_PASSWORD: facilities
      POSTGRES_DB: facilities
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: